<a href="https://colab.research.google.com/github/Aurelien-Be/Aurelien-Be/blob/main/japprendspytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt

print (torch.__version__)

2.6.0+cu124


In [ ]:
#introductions to tensors

#scalar

scalar = torch.tensor(7)  #tensors are created using torch.tensor()
scalar  #a scalar is a tensor with no dimensions, meaning it doesn’t have rows,
        #columns, or any extra structure



tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as Python int
scalar.item()

7

In [ ]:
#Vector

vector = torch.tensor([7,7])
vector
#a vector has one dimension but different values, the position of each element is important, useful for structured datas

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape #how many elements

torch.Size([2])

In [3]:
#MATRIX
# Define MATRIX as a list of lists to represent a 2x2 tensor (matrix)
# Each inner list corresponds to a row in the matrix
MATRIX = torch.tensor([[7, 8],     # First row of the matrix containing two elements: 7 and 8
          [9, 10]])    # Second row of the matrix containing two elements: 9 and 10

# Explanation of the matrix:
# 1. Structure:
#    - MATRIX is essentially a 2-dimensional structure.
#    - It has 2 rows and 2 columns.
#
# 2. Representation:
#    - The first inner list [7, 8] represents the first row.
#    - The second inner list [9, 10] represents the second row.
#
# 3. Usage:
#    - In many programming scenarios and in linear algebra, such a matrix can
#      be used to perform a variety of operations such as matrix addition,
#      multiplication, or as a way to represent data in a structured, 2D format.
#
# 4. Transition to Tensor Libraries:
#    - When using libraries like PyTorch or NumPy, you can convert this list of lists
#      into a tensor or array for efficient numerical operations.

In [4]:
MATRIX.ndim
#2 dimensions

2

In [5]:
MATRIX[1]

tensor([ 9, 10])

In [6]:
MATRIX.shape

torch.Size([2, 2])

In [8]:
#TENSOR
# Creating a 3D tensor with shape [1, 3, 3]
# - Dimension 0 (outermost): 1 element (single batch/item)
# - Dimension 1 (middle): 3 rows
# - Dimension 2 (innermost): 3 columns per row
# This tensor can represent a single 3x3 matrix, or one 3x3 image in a batch


TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,6]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [9]:
TENSOR.ndim

3

In [10]:
TENSOR.shape

torch.Size([1, 3, 3])

In [11]:
TENSOR[0]
# Indexing the 0th (and only) element along the first dimension
# This returns a 2D tensor with shape [3, 3] by removing the outermost dimension
# Equivalent to accessing the first (and only) batch/item in our tensor

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])

In [21]:
#test
TENSOR1 = torch.tensor([
    [
        [1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]
    ],
    [
        [6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]
    ]
])
#Each sub-tensor at the same level must have the same shape

#This is a fundamental rule in PyTorch (and most tensor libraries): when creating multi-dimensional tensors, all elements at the same nesting level must maintain consistent dimensions to ensure a regular structure.



In [22]:
TENSOR1.shape

torch.Size([2, 3, 3])